---
title: "run_sptype"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{run_sptype}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```


## Download an example dataset


```{r install-pbmc3k eval = FALSE}
# 1. install SeuratData
pak::pkg_install("satijalab/seurat-data")

# 2. Install the 'pbmc3k' dataset
library(SeuratData)
options(timeout = 600) # to set the timeout limit for download.packages() to 600s

InstallData("stxBrain")

# 3. Load the dataset -> seurat object
library(Seurat)
brain <- LoadData("stxBrain", type = "anterior1")
```


## Prepare data
```{r}
brain <- SCTransform(brain, assay = "Spatial", verbose = FALSE)
brain <- RunPCA(brain, assay = "SCT", verbose = FALSE)
brain <- FindNeighbors(brain, reduction = "pca", dims = 1:30)
brain <- FindClusters(brain, verbose = FALSE)
brain <- RunUMAP(brain, reduction = "pca", dims = 1:30)
```

## Run scType 
```{r setup}
library(sctype)

brain <- run_sptype(brain, known_tissue_type = "Brain", assay = "SCT")

# Overlay annotation on DimPlots
SpatialDimPlot(brain, group.by = "sctype_classification")
```
